name: dogfood

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:
    inputs:
      publish:
        description: Select the host's OS for the real publish operation ('linux', 'windows', 'mac')
        required: false
        default: 'dry-run'


jobs:
  dogfood-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./
        with:
          project-name: pypi-publish-with-poetry-dogfood
          pypi-token: ${{ secrets.PYPI_TOKEN_DOGFOOD }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.event.inputs.publish != 'linux' }}
          tag-prefix: dogfood-linux-
          pyproject-folder: ./pypi-publish-with-poetry-dogfood

  dogfood-windows:
    needs: dogfood-linux
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./
        with:
          project-name: pypi-publish-with-poetry-dogfood
          pypi-token: ${{ secrets.PYPI_TOKEN_DOGFOOD }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.event.inputs.publish != 'windows' }}
          tag-prefix: dogfood-windows-
          pyproject-folder: ./pypi-publish-with-poetry-dogfood

  dogfood-mac:
    needs: dogfood-windows
    runs-on: macos-11

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Publish to pypi
        uses: ./
        with:
          project-name: pypi-publish-with-poetry-dogfood
          pypi-token: ${{ secrets.PYPI_TOKEN_DOGFOOD }}
          pre-release: ${{ github.ref != 'refs/heads/main' }}
          dry-run: ${{ github.event.inputs.publish != 'mac' }}
          tag-prefix: dogfood-mac-
          pyproject-folder: ./pypi-publish-with-poetry-dogfood
